In [1]:
import pandas as pd

df = pd.read_json('data/dialogue_test.json', lines=True)
df.head()

,dialogue,summary,summaries
0,user: I need a hotel with free wifi and free p...,User Profile: Pengguna mencari akomodasi dan r...,[{'pos': 'User Profile: Pengguna mencari akomo...
1,user: Looking for a place to eat in the city c...,User Profile: Pengguna sedang mencari tempat m...,[{'pos': 'User Profile: Pengguna sedang mencar...

In [2]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("Qwen/qwen2.5-0.5B")  # atau model kamu

df['dialogue_len_token'] = df['dialogue'].apply(
    lambda x: len(tokenizer.encode(x, add_special_tokens=False))
)

df['summary_len_token'] = df['summary'].apply(
    lambda x: len(tokenizer.encode(x, add_special_tokens=False))
)

/home/qiscus/Coresearch_ITB_Qiscus/repo_alan/SLM Summarization/symbolic_distill_contrastive_summ/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
df.head()

,dialogue,summary,summaries,dialogue_len_token,summary_len_token
0,user: I need a hotel with free wifi and free p...,User Profile: Pengguna mencari akomodasi dan r...,[{'pos': 'User Profile: Pengguna mencari akomo...,256,128
1,user: Looking for a place to eat in the city c...,User Profile: Pengguna sedang mencari tempat m...,[{'pos': 'User Profile: Pengguna sedang mencar...,246,128

In [4]:
max_input_len = 256
max_output_len = 128

def truncate_text(text, max_len):
    tokens = tokenizer.encode(text, add_special_tokens=False)
    tokens = tokens[:max_len]
    return tokenizer.decode(tokens, skip_special_tokens=True)

df['dialogue'] = df['dialogue'].apply(lambda x: truncate_text(x, max_input_len))
df['summary'] = df['summary'].apply(lambda x: truncate_text(x, max_output_len))

In [7]:
df[['dialogue','summary','summaries']].to_json(
    'data/dialogue_test.json',
    orient='records',
    lines=False,
    force_ascii=False
)

In [ ]:
preds = [[  2780   2732  54404  52122   9101    933    268   1833  46968   2732
          54404  52122   3101     11  36686  61275  51518   2780   2732  54404
   52122  10371   1982  37527     74   2863   1853  74576    266    595
    5094   9101  17324    316    347  10215  10371   1982  37527     74
    2863   1853  23641   9101  17324    316    347  10215  10371   1982
   37527     74   2863   1853  23641   9101    933    268  75582  61177
     276 151643  10371]
 [  2780   2732  54404  20414  66518   3664    300  97114    306     84
    9101    933    268  75582  61177    276   2732  54404  20414    595
    5094   9101    933    268  75582  61177    276    264   9198  10371
    1982   7523  47656   6996   1982   7523  47656   6996   1982   7523
    9101    933    268  75582 151643  10371   -100   -100   -100   -100
    -100   -100   -100   -100   -100   -100   -100   -100   -100   -100
    -100   -100   -100]]